routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','StaticPagesController@home')->name('home');
Route::get('/help','StaticPagesController@help')->name('help');
Route::get('/about','StaticPagesController@about')->name('about');

// signup
Route::get('/signup','UsersController@create')->name('signup');
Route::resource('users', 'UsersController');
Route::get('/users/{user}', 'UsersController@show')->name('users.show');

// login
Route::get('login', 'SessionsController@create')->name('login');  //登录
Route::post('login', 'SessionsController@store')->name('login');  //创建新的会话
Route::delete('logout', 'SessionsController@destroy')->name('logout');  //销毁会话
// Route::get('/', function () {
//     return view('welcome');
// });

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    // protected $table = 'my_articles';
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    
    protected $table = 'users';
    public function gravatar($size = '100')
    {
        $hash =  md5(strtolower(trim($this->attributes['email'])));
        return "http://www.gravatar.com/avatar/$hash?s=$size";
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SessionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;

class SessionsController extends Controller
{
    public function create()
    {
        return view('sessions.create');
    }

    public function store(Request $request)
    {
        $credentials = $this->validate($request, [
           'email' => 'required|email|max:255',
           'password' => 'required'
        ]);

        if (Auth::attempt($credentials, $request->has('remember'))) {
            session()->flash('success', '欢迎回来！');
            return redirect()->route('users.show', [Auth::user()]);
        } else {
            session()->flash('danger', '很抱歉，您的邮箱和密码不匹配');
            return redirect()->back();
        }
    }
    /* 退出登陆 */
    public function destroy()
    {
        Auth::logout();
        session()->flash('success', '您已成功退出！');
        return redirect('login');
    }
}

app/Http/Controllers/StaticPagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class StaticPagesController extends Controller
{
    public function home()
    {
    	return view('static_pages/home');
    }

    public function help()
    {
    	return view('static_pages/help');
    }

    public function about()
    {
    	return view('static_pages/about');
    }

}
?>

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Models\User;
use Auth;
class UsersController extends Controller
{
    public function create()
    {
			return view('users.create');
    }

    public function show(User $user)
    {
			return view('users.show', compact('user'));
    }

    public function store(Request $request)
    {
			$this->validate($request, [
				'name' => 'required|max:50',
				'email' => 'required|email|unique:users|max:255',
				'password' => 'required|confirmed|min:6'
            ]);
            
            $user = User::create([
                'name' => $request->name,
                'email' => $request->email,
                'password' => bcrypt($request->password),
            ]);
            Auth::login($user);
            session()->flash('success', '欢迎,您将在这里开启一段新的旅程~');
			return redirect()->route('users.show', [$user]);
    }
}

resources/views/layouts/_footer.blade.php
<div class="col-md-12">
  <footer class="footer">
    <small class="slogon">
      <img class="brand-icon" src="https://iocaffcdn.phphub.org/uploads/images/201612/12/1/iq7WQc2iuW.png?imageView2/1/w/34/h/34">
      <a href="https://laravel-china.org/courses">刻意练习，每日精进</a>
    </small>
    <nav>
      <ul>
        <li><a href="{{ route('about') }}">关于</a></li>
      </ul>
    </nav>
  </footer>
</div>

resources/views/layouts/_header.blade.php
<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="container">
			<div class="col-md-offset-1 col-md-10">
				<a href="/" id="logo">Sample App</a>
				<nav>
					<ul class="nav navbar-nav navbar-right">
						@if (Auth::check())
							<li><a href="#">用户列表</a></li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									{{ Auth::user()->name }} <b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li><a href="{{ route('users.show', Auth::user()->id) }}">个人中心</a></li>
									<li><a href="#">编辑资料</a></li>
									<li class="divider"></li>
									<li>
										<a id="logout" href="#">
											<form action="{{ route('logout') }}" method="POST">
												{{ csrf_field() }}
												{{ method_field('DELETE') }}
												<button class="btn btn-block btn-danger" type="submit" name="button">退出</button>
											</form>
										</a>
									</li>
								</ul>
							</li>
						@else
							<li><a href="{{ route('help') }}">帮助</a></li>
							<li><a href="{{ route('login') }}">登录</a></li>
						@endif
					</ul>
				</nav>
			</div>
		</div>
	</header>

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html>
  <head>
    <title>@yield('title', 'Sample App') - Laravel 入门教程</title>
    <link rel="stylesheet" href="/css/app.css">
  </head>
  <body>
    @include('layouts._header')

    <div class="container">
      <div class="col-md-offset-1 col-md-10">
        @include('shared._messges')
        @yield('content')
        @include('layouts._footer')
      </div>
    </div>

    <script src="/js/app.js"></script>
  </body>
</html>

resources/views/shared/_errors.blade.php
@if (count($errors) > 0)
  <div class="alert alert-danger">
    <ul>
      @foreach($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

resources/views/shared/_messges.blade.php
@foreach (['danger', 'warning', 'success', 'info'] as $msg)
  @if(session()->has($msg))
    <div class="flash-message">
      <p class="alert alert-{{ $msg }}">
        {{ session()->get($msg) }}
      </p>
    </div>
  @endif
@endforeach

resources/views/shared/_user_info.blade.php
<a href="{{ route('users.show', $user->id) }}">
    <img src="{{ $user->gravatar('140') }}" alt="{{ $user->name }}" class="gravatar">
</a>
<h1>{{ $user->name }}</h1>

resources/views/static_pages/about.blade.php
@extends('layouts.default')
@section('title','关于')

@section('content')
	<h1>关于</h1>
@stop

resources/views/static_pages/help.blade.php
@extends('layouts.default')
@section('title','帮助')

@section('content')
	<h1>帮助页</h1>
@stop

resources/views/static_pages/home.blade.php
@extends('layouts.default')
@section('title', '主页')
@section('content')
	<div class="jumbotron">
		<h1>Hello Laravel</h1>
		<p class="lead">
			你现在看到的是
			<a href="https://laravel-china.org/courses/laravel-essential-training-5.5">Laravel 入门教程</a> 的示例项目主页。
		</p>
		<p>一切，将从这里开始</p>
		<p>
			<a class="btn btn-lg btn-success" href="{{ route('signup') }}" role="button">现在注册</a>
		</p>
	</div>
@stop

resources/views/users/create.blade.php
@extends('layouts.default')
@section('title','注册')

@section('content')
<div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h5>注册</h5>
      </div>
      <div class="panel-body">
        @include('shared._errors')
  
        <form method="POST" action="{{ route('users.store') }}">
            {{ csrf_field() }}
  
            <div class="form-group">
              <label for="name">名称：</label>
              <input type="text" name="name" class="form-control" value="{{ old('name') }}">
            </div>
  
            <div class="form-group">
              <label for="email">邮箱：</label>
              <input type="text" name="email" class="form-control" value="{{ old('email') }}">
            </div>
  
            <div class="form-group">
              <label for="password">密码：</label>
              <input type="password" name="password" class="form-control" value="{{ old('password') }}">
            </div>
  
            <div class="form-group">
              <label for="password_confirmation">确认密码：</label>
              <input type="password" name="password_confirmation" class="form-control" value="{{ old('password_confirmation') }}">
            </div>
  
            <button type="submit" class="btn btn-primary">注册</button>
        </form>
      </div>
    </div>
  </div>
  @stop

resources/views/users/show.blade.php
@extends('layouts.default')
@section('title', $user->name)
@section('content')
	<div class="row">
		<div class="col-md-offset-2 col-md-8">
			<div class="col-md-12">
				<div class="col-md-offset-2 col-md-8">
					<section class="user_info">
						@include('shared._user_info', ['user' => $user])
					</section>
				</div>
			</div>
		</div>
	</div>
@stop